//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_process.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("data_process.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似     
        ///    你好，希望数据处理工具可以帮助你完成一些数据相关任务，
        ///    使用的过程中如果有任何的意见，问题，请一定与我联系：
        ///    
        ///    讨论群:    601169305
        ///    QQ:        2146651351
        ///    微信:      jianzhi_ai
        ///    微信公号:  AIChangeLife 
        ///    官网:      http://www.simplestai.com/webkits
        ///    
        ///    使用方法简单，官网有精炼的视频教程。
        ///    
        ///    如果有需要开发插件功能（对抓取数据过程加入自己的处理
        ///    方法），我们免费为你开发（过于复杂的功能提供支持）。
        ///    
        ///    有技术，资源相互合作需求（合理的产品和需求（如教育，培
        ///    训领域）不收费），请与我们联系。
        ///    
        ///    如果软件使用体验不错，请支持我们，使我们可以有足够的
        ///    时间，尽心的开发出更强化完善，易用，智能的功能。
        ///    
        ///    数据收集功能的目的是从互联网上收集开放的信息，是否违
        ///    背数据本身的知识产权等相关权利由使 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
